name: Add Badges
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/add-badges@v1
        env:
          repo_url: ${{ github.event.repository.html_url }}
          repo_name: ${{ github.event.repository.name }}
          repo_owner: ${{ github.event.repository.owner.login }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          center: true
          badges: |
            [
              [
                {
                  "badge": "https://img.shields.io/github/license/paulosabayomi/treeSpider?style=flat-square",
                  "alt": "MIT License",
                  "link": "${{ env.repo_url }}/blob/main/LICENSE"
                },
                {
                  "badge": "https://img.shields.io/badge/language-TypeScript-blue.svg?style=flat-square",
                  "alt": "Language",
                  "link": "https://www.typescriptlang.org"
                },
                {
                  "badge": "https://img.shields.io/badge/PRs-Welcome-brightgreen.svg?style=flat-square",
                  "alt": "PRs Welcome",
                  "link": "${{ env.repo_url }}/pulls"
                },
                {
                  "badge": "https://img.shields.io/static/v1?label=&labelColor=505050&message=marketplace&color=0076D6&style=flat-square&logo=google-chrome&logoColor=0076D6",
                  "alt": "website",
                  "link": "https://github.com/paulosabayomi/treeSpider"
                }
              ],
              [
                {
                  "badge": "https://github.com/paulosabayomi/treeSpider/actions/workflows/package.yml/badge.svg",
                  "alt": "Package",
                  "link": "${{ env.repo_url }}/actions/workflows/package.yml"
                },
                {
                  "badge": "https://github.com/paulosabayomi/treeSpider/actions/workflows/npm-publish.yml/badge.svg",
                  "alt": "Publish to npm",
                  "link": "https://github.com/paulosabayomi/treeSpider/actions/workflows/npm-publish.yml"
                },
                {
                  "badge": "https://github.com/paulosabayomi/treeSpider/actions/workflows/tests.yml/badge.svg",
                  "alt": "Tests",
                  "link": "https://github.com/paulosabayomi/treeSpider/actions/workflows/tests.yml"
                }
              ]
            ]